repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: local-precommit-checks
        name: Local precommit checks (tests + generator)
        entry: ./tools/scripts/precommit_check.sh
        language: script
        stages: [commit]
