# This file is a generated SKiDL library fixture used only for tests.
# It contains large, machine-generated literals which violate formatting
# rules; skip ruff checks for this generated file.
# ruff: noqa

from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = "0.0.1"

__init__ = SchLib(tool=SKIDL).add_parts(
    *[
        Part(
            **{
                "name": "RP2040",
                "dest": TEMPLATE,
                "tool": SKIDL,
                "aliases": Alias({"RP2040"}),
                "ref_prefix": "U",
                "fplist": ["Package_QFN:QFN-56-1EP_7x7mm_P0.4mm_EP5.5x5.5mm"],
                "footprint": "",
                "keywords": "",
                "description": "",
                "datasheet": "https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf",
                "pins": [
                    Pin(num="2", name="GPIO0", func=pin_types.BIDIR),
                    Pin(num="3", name="GPIO1", func=pin_types.BIDIR),
                    Pin(num="4", name="GPIO2", func=pin_types.BIDIR),
                    Pin(num="5", name="GPIO3", func=pin_types.BIDIR),
                    Pin(num="6", name="GPIO4", func=pin_types.BIDIR),
                    Pin(num="7", name="GPIO5", func=pin_types.BIDIR),
                    Pin(num="8", name="GPIO6", func=pin_types.BIDIR),
                    Pin(num="9", name="GPIO7", func=pin_types.BIDIR),
                    Pin(num="11", name="GPIO8", func=pin_types.BIDIR),
                    Pin(num="12", name="GPIO9", func=pin_types.BIDIR),
                    Pin(num="13", name="GPIO10", func=pin_types.BIDIR),
                    Pin(num="14", name="GPIO11", func=pin_types.BIDIR),
                    Pin(num="15", name="GPIO12", func=pin_types.BIDIR),
                    Pin(num="16", name="GPIO13", func=pin_types.BIDIR),
                    Pin(num="17", name="GPIO14", func=pin_types.BIDIR),
                    Pin(num="18", name="GPIO15", func=pin_types.BIDIR),
                    Pin(num="27", name="GPIO16", func=pin_types.BIDIR),
                    Pin(num="28", name="GPIO17", func=pin_types.BIDIR),
                    Pin(num="29", name="GPIO18", func=pin_types.BIDIR),
                    Pin(num="30", name="GPIO19", func=pin_types.BIDIR),
                    Pin(num="31", name="GPIO20", func=pin_types.BIDIR),
                    Pin(num="32", name="GPIO21", func=pin_types.BIDIR),
                    Pin(num="34", name="GPIO22", func=pin_types.BIDIR),
                    Pin(num="35", name="GPIO23", func=pin_types.BIDIR),
                    Pin(num="36", name="GPIO24", func=pin_types.BIDIR),
                    Pin(num="37", name="GPIO25", func=pin_types.BIDIR),
                    Pin(num="38", name="GPIO26/ADC0", func=pin_types.BIDIR),
                    Pin(num="39", name="GPIO27/ADC1", func=pin_types.BIDIR),
                    Pin(num="40", name="GPIO28/ADC2", func=pin_types.BIDIR),
                    Pin(num="41", name="GPIO29/ADC3", func=pin_types.BIDIR),
                    Pin(num="51", name="QSPI_SD3", func=pin_types.BIDIR),
                    Pin(num="52", name="QSPI_SCLK", func=pin_types.BIDIR),
                    Pin(num="53", name="QSPI_SD0", func=pin_types.BIDIR),
                    Pin(num="54", name="QSPI_SD2", func=pin_types.BIDIR),
                    Pin(num="55", name="QSPI_SD1", func=pin_types.BIDIR),
                    Pin(num="56", name="QSPI_CSN", func=pin_types.BIDIR),
                    Pin(num="20", name="XIN", func=pin_types.INPUT),
                    Pin(num="21", name="XOUT", func=pin_types.OUTPUT),
                    Pin(num="24", name="SWCLK", func=pin_types.INPUT),
                    Pin(num="25", name="SWD", func=pin_types.BIDIR),
                    Pin(num="26", name="RUN", func=pin_types.INPUT),
                    Pin(num="19", name="TESTEN", func=pin_types.PASSIVE),
                    Pin(num="47", name="USB_DP", func=pin_types.BIDIR),
                    Pin(num="46", name="USB_DM", func=pin_types.BIDIR),
                    Pin(num="45", name="VREG_VOUT", func=pin_types.OUTPUT),
                    Pin(num="44", name="VREG_VIN", func=pin_types.INPUT),
                    Pin(num="48", name="USB_VDD", func=pin_types.PWRIN),
                    Pin(num="1", name="IOVDD", func=pin_types.PWRIN),
                    Pin(num="10", name="IOVDD", func=pin_types.PWRIN),
                    Pin(num="22", name="IOVDD", func=pin_types.PWRIN),
                    Pin(num="33", name="IOVDD", func=pin_types.PWRIN),
                    Pin(num="42", name="IOVDD", func=pin_types.PWRIN),
                    Pin(num="49", name="IOVDD", func=pin_types.PWRIN),
                    Pin(num="23", name="DVDD", func=pin_types.PWRIN),
                    Pin(num="50", name="DVDD", func=pin_types.PWRIN),
                    Pin(num="43", name="ADC_AVDD", func=pin_types.PWRIN),
                    Pin(num="57", name="GND", func=pin_types.PWRIN),
                    Pin(num="1", name="VCC", func=pin_types.PWRIN),
                    Pin(num="2", name="GND", func=pin_types.PWRIN),
                    Pin(num="4", name="VBUS", func=pin_types.PWRIN),
                    Pin(num="9", name="RESET", func=pin_types.INPUT),
                    Pin(num="3", name="GPIO0", func=pin_types.BIDIR),
                    Pin(num="5", name="GPIO1", func=pin_types.BIDIR),
                    Pin(num="6", name="GPIO2", func=pin_types.BIDIR),
                    Pin(num="7", name="GPIO3", func=pin_types.BIDIR),
                    Pin(num="8", name="GPIO4", func=pin_types.BIDIR),
                    Pin(num="10", name="SWDIO", func=pin_types.BIDIR),
                    Pin(num="11", name="SWCLK", func=pin_types.BIDIR),
                ],
                "unit_defs": [
                    {
                        "label": "u",
                        "num": 0,
                        "pin_nums": [
                            "41",
                            "16",
                            "26",
                            "4",
                            "40",
                            "2",
                            "57",
                            "17",
                            "51",
                            "10",
                            "18",
                            "3",
                            "52",
                            "19",
                            "27",
                            "53",
                            "22",
                            "28",
                            "54",
                            "55",
                            "47",
                            "29",
                            "33",
                            "5",
                            "30",
                            "46",
                            "56",
                            "6",
                            "31",
                            "42",
                            "7",
                            "12",
                            "32",
                            "20",
                            "45",
                            "34",
                            "8",
                            "49",
                            "43",
                            "35",
                            "44",
                            "21",
                            "9",
                            "36",
                            "23",
                            "11",
                            "25",
                            "37",
                            "48",
                            "24",
                            "50",
                            "38",
                            "13",
                            "14",
                            "39",
                            "1",
                            "15",
                        ],
                    },
                    {
                        "label": "uA",
                        "num": 1,
                        "pin_nums": [
                            "11",
                            "16",
                            "41",
                            "4",
                            "40",
                            "26",
                            "2",
                            "17",
                            "51",
                            "10",
                            "57",
                            "5",
                            "3",
                            "18",
                            "52",
                            "19",
                            "27",
                            "53",
                            "22",
                            "2",
                            "6",
                            "28",
                            "54",
                            "55",
                            "47",
                            "29",
                            "33",
                            "5",
                            "30",
                            "8",
                            "56",
                            "46",
                            "6",
                            "31",
                            "42",
                            "7",
                            "7",
                            "12",
                            "32",
                            "20",
                            "45",
                            "8",
                            "34",
                            "49",
                            "35",
                            "43",
                            "4",
                            "9",
                            "9",
                            "21",
                            "44",
                            "1",
                            "36",
                            "23",
                            "10",
                            "11",
                            "37",
                            "24",
                            "48",
                            "38",
                            "50",
                            "13",
                            "3",
                            "14",
                            "39",
                            "1",
                            "25",
                            "15",
                        ],
                    },
                ],
            }
        )
    ]
)
