name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: python -m pip install -r tools/requirements-dev.txt
      - name: Run tests
        run: pytest -q
      - name: Generate BOM & placement
        run: |
          python tools/scripts/generate_bom.py --out tools/output/bom.csv
          python tools/scripts/generate_placement.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts
          path: tools/output
